name: eval_aksara
channels:
  - conda-forge
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.1=h0c1763c_0
  - libuuid=2.41.2=h5347b49_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - anyio==4.12.0
      - apache-tvm-ffi==0.1.5
      - astor==0.8.1
      - async-timeout==5.0.1
      - asyncio==4.0.0
      - attrs==25.4.0
      - blake3==1.0.8
      - cachetools==6.2.3
      - cbor2==5.7.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.2.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - compressed-tensors==0.12.2
      - cuda-bindings==13.1.1
      - cuda-pathfinder==1.3.3
      - cuda-python==13.1.1
      - cupy-cuda12x==13.6.0
      - datasets==4.4.1
      - depyf==0.20.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.3.0
      - exceptiongroup==1.3.1
      - fastapi==0.124.4
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.6.0
      - fastar==0.8.0
      - fastrlock==0.8.3
      - filelock==3.20.0
      - flashinfer-python==0.5.2
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gguf==0.17.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.12.0
      - jiwer==4.0.0
      - jmespath==1.0.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lark==1.2.2
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mistral-common==1.8.6
      - model-hosting-container-standards==0.1.11
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.4.2
      - ninja==1.13.0
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.16.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.3.3
      - nvidia-ml-py==13.590.44
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.11.0
      - openai-harmony==0.0.8
      - opencv-python-headless==4.12.0.88
      - outlines-core==0.2.11
      - packaging==25.0
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post7
      - pillow==12.0.0
      - portalocker==3.2.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pybase64==1.4.3
      - pycountry==24.6.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - rapidfuzz==3.14.3
      - ray==2.52.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.17.0
      - rignore==0.7.6
      - rpds-py==0.30.0
      - sacrebleu==2.5.1
      - safetensors==0.7.0
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.47.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.50.0
      - supervisor==4.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.5.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vllm==0.11.2
      - watchfiles==1.1.1
      - websockets==15.0.1
      - xformers==0.0.33.post1
      - xgrammar==0.1.25
      - xxhash==3.6.0
      - yarl==1.22.0
